In [1]:
! wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv

--2025-09-29 08:46:31--  https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 874188 (854K) [text/plain]
Saving to: ‘car_fuel_efficiency.csv’

car_fuel_efficiency 100%[===================>] 853.70K  3.70MB/s    in 0.2s    

2025-09-29 08:46:32 (3.70 MB/s) - ‘car_fuel_efficiency.csv’ saved [874188/874188]



In [97]:
import pandas as pd
import numpy as np

In [98]:
df = pd.read_csv('/content/car_fuel_efficiency.csv')

In [99]:
df.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

Question 1: Pandas version

In [88]:
pd.__version__

'2.2.2'

Question 2: Records count from df shape

In [100]:
df.shape

(9704, 11)

Question 3: How many fuel types present?

In [101]:
df['fuel_type'].value_counts()

fuel_type
Gasoline    4898
Diesel      4806
Name: count, dtype: int64

Question 4: How many columns have missing values?

In [102]:
missing_val = 0
for col in df.columns:
  if df[col].isna().sum() > 0:
    missing_val += 1

print(f"{missing_val} columns in the dataset have missing values")

4 columns in the dataset have missing values


Question 5: Maximum fuel efficiency of cars from Asia?

In [14]:
df[df['origin'] == 'Asia'].describe()

engine_displacement  num_cylinders   horsepower  vehicle_weight  \
count          3247.000000    3099.000000  3013.000000     3247.000000   
mean            200.052356       4.010326   150.303352     3006.292228   
std              49.287252       1.971199    30.257169      502.434626   
min              30.000000       0.000000    40.000000     1223.298226   
25%             170.000000       3.000000   130.000000     2665.518985   
50%             200.000000       4.000000   150.000000     2988.585737   
75%             230.000000       5.000000   171.000000     3345.355571   
max             370.000000      11.000000   245.000000     4661.144932   

       acceleration   model_year    num_doors  fuel_efficiency_mpg  
count   2933.000000  3247.000000  3072.000000          3247.000000  
mean      15.036754  2011.489375    -0.001628            14.973830  
std        2.488340     6.704607     1.051428             2.578345  
min        6.400000  2000.000000    -4.000000             6.886245  
25%       13.300000  2006.000000    -1.000000            13.252010  
50%       15.100000  2012.000000     0.000000            15.034670  
75%       16.700000  2017.000000     1.000000            16.726318  
max       22.700000  2023.000000     4.000000            23.759123

In [93]:
df[df['origin'] == 'Asia']['fuel_efficiency_mpg'].describe().loc['max']

np.float64(23.759122836520497)

Question 6. Median value of horsepower

In [103]:
# Find the median value of the horsepower column in the dataset.
df['horsepower'].median()

149.0

In [104]:
# Calculate the most frequent value of the same horsepower column.
df['horsepower'].mode()

0    152.0
Name: horsepower, dtype: float64

In [105]:
# Use fillna method to fill the missing values in the horsepower column with the most frequent value from the previous step
df['horsepower'] = df['horsepower'].fillna(df['horsepower'].mode().to_list()[0])

In [106]:
# Calculate the median value of horsepower again
df['horsepower'].median()

152.0

Question 7: Sum of Weights

In [109]:
df_asia = df[df['origin'] == 'Asia'][['vehicle_weight', 'model_year']]

In [110]:
df_asia.head(7)

vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016
34     2844.227534        2014
38     3761.994038        2019

In [118]:
X = df_asia.head(7).to_numpy()
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [119]:
XTX = np.dot(X.T, X)
XTX

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [120]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv.shape

(2, 2)

In [121]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [122]:
X.T.shape

(2, 7)

In [123]:
_w = np.dot(XTX_inv, X.T)
_w.shape

(2, 7)

In [125]:
w = np.dot(_w, y)
w.shape

(2,)

In [126]:
w

array([0.01386421, 0.5049067 ])

In [127]:
w.sum()

np.float64(0.5187709081074016)